import fs from 'node:fs';
import path from 'node:path';
import { CUSTOM_SETS, loadIconData, root, scanIconUsage, validateCatalog } from './audit-icon-usage.mjs';

try {
    const catalog = JSON.parse(fs.readFileSync(path.join(root, 'resources/icons/catalog.json'), 'utf8'));
    const data = loadIconData();
    const usage = scanIconUsage();
    // Validate every set and used source token before writing any generated file.
    const mappings = validateCatalog(catalog, data, usage);
    const output = path.join(root, 'public/icons');
    const artifacts = new Map();
    const report = {};
    const previewSets = {};
    const notices = ['# Bundled icon attribution', '', 'Generated from the locked @iconify-json packages. See each upstream license:', ''];

    for (const set of CUSTOM_SETS) {
        const label = catalog.sets[set];
        const info = JSON.parse(fs.readFileSync(path.join(root, 'node_modules/@iconify-json', set, 'info.json'), 'utf8'));
        notices.push(`- ${label}: ${info.author.name} — ${info.license.title} — ${info.license.url}`);
        const resolved = mappings[set];
        const groups = new Map();
        for (const [semantic, name] of Object.entries(resolved)) {
            if (!groups.has(name)) groups.set(name, []);
            groups.get(name).push(semantic);
        }
        const iconUri = (name) => {
            const icon = data[set].icons[name];
            // Iconify omits dimensions equal to its 16px default (not 24px).
                        // Keep the native coordinate system while sharing a 24px output box.
                        const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="${icon.left ?? data[set].left ?? 0} ${icon.top ?? data[set].top ?? 0} ${icon.width ?? data[set].width ?? 16} ${icon.height ?? data[set].height ?? 16}">${icon.body}</svg>`;
            return 'data:image/svg+xml,' + encodeURIComponent(svg).replaceAll("'", '%27');
        };
        let css = `/* Generated by npm run icons:build. ${label}; attribution: /icons/NOTICE.md */\n`;
        for (const [name, semantics] of groups) {
            const selectors = semantics.map((semantic) => `:is(.fa,.fas,.far,.fa-solid,.fa-regular).fa-${semantic}:not(.fab):not(.fa-brands)::before`).join(',\n');
            css += `${selectors}{content:""!important;display:inline-block;width:1em;height:1em;vertical-align:-.125em;background-color:currentColor;-webkit-mask:url("${iconUri(name)}") center/contain no-repeat;mask:url("${iconUri(name)}") center/contain no-repeat;}\n`;
        }
        artifacts.set(path.join(output, `${set}.css`), css);
        // The picker uses these URIs as masks, not <img> sources. Preserve currentColor
        // and the complete {sets: {id: {semantic: dataURI}}} interface.
        previewSets[set] = Object.fromEntries(Object.entries(resolved).map(([semantic, name]) => [semantic, iconUri(name)]));
        report[set] = { mapped: Object.keys(resolved).length, fallback: [], icons: resolved };
        console.log(`${set}: ${Object.keys(resolved).length} mapped icons (${Buffer.byteLength(css)} bytes)`);
    }
    artifacts.set(path.join(output, 'manifest.json'), JSON.stringify(report, null, 2) + '\n');
    artifacts.set(path.join(root, 'resources/icons/preview-manifest.json'), JSON.stringify({ sets: previewSets }) + '\n');
    artifacts.set(path.join(output, 'NOTICE.md'), notices.join('\n') + '\n');
    fs.mkdirSync(output, { recursive: true });
    for (const [file, content] of artifacts) fs.writeFileSync(file, content);
    // Remove only our obsolete generated CSS, never unrelated hand-authored assets.
    for (const entry of fs.readdirSync(output, { withFileTypes: true })) {
        if (!entry.isFile() || !entry.name.endsWith('.css') || CUSTOM_SETS.includes(entry.name.slice(0, -4))) continue;
        const file = path.join(output, entry.name);
        if (fs.readFileSync(file, 'utf8').startsWith('/* Generated by npm run icons:build.')) fs.unlinkSync(file);
    }
    console.log(`Icon coverage passed: ${usage.used.size} source names, ${Object.keys(catalog.icons).length} concepts, ${Object.keys(catalog.aliases).length} aliases; no missing mappings.`);
} catch (error) {
    console.error(error.message);
    process.exitCode = 1;
}
